//! Export-parity: the pure-Rust tree-walker must reproduce `booster.predict` to
//! 1e-6 on the committed fixture (generated by `python -m model_lab.export_champion`,
//! including NaN- and exactly-0-bearing rows that exercise native-missing /
//! `missing_type=Zero` routing). This is the #1 correctness gate for shadow.

use std::path::PathBuf;

use serde::Deserialize;
use shadow::{FULL_FEATURES, LgbmModel};

#[derive(Deserialize)]
struct ParityFixture {
    model_file: String,
    feature_names: Vec<String>,
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct Case {
    /// `null` = NaN (native-missing).
    features: Vec<Option<f64>>,
    expected_p_up: f64,
}

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

#[test]
fn walker_matches_booster_predict_to_1e6() {
    let dir = fixture_dir();
    let text = std::fs::read_to_string(dir.join("parity_cases.json"))
        .expect("commit crates/shadow/tests/fixtures/parity_cases.json (run export_champion)");
    let fixture: ParityFixture = serde_json::from_str(&text).expect("parity_cases.json parses");

    // Feature order is the model's positional contract.
    assert_eq!(
        fixture.feature_names.as_slice(),
        FULL_FEATURES,
        "fixture feature order must equal FULL_FEATURES"
    );

    let model = LgbmModel::load(&dir.join(&fixture.model_file)).expect("model.txt loads");
    assert_eq!(model.num_features(), 24, "champion has 24 features");
    assert!(model.num_trees() >= 1, "model has trees");

    assert!(!fixture.cases.is_empty(), "fixture has cases");
    let mut max_abs = 0.0_f64;
    for (i, case) in fixture.cases.iter().enumerate() {
        assert_eq!(case.features.len(), 24, "case {i} has 24 features");
        let feats: Vec<f32> = case
            .features
            .iter()
            .map(|v| v.map_or(f32::NAN, |x| x as f32))
            .collect();
        let got = model.predict(&feats);
        let diff = (got - case.expected_p_up).abs();
        max_abs = max_abs.max(diff);
        assert!(
            diff < 1e-6,
            "case {i}: got {got}, expected {}, |Δ| {diff:.3e}",
            case.expected_p_up
        );
    }
    eprintln!(
        "export parity: {} cases, max |Δ| = {max_abs:.3e}",
        fixture.cases.len()
    );
}
